name: "CheckoutRepoGit"
description: | 
  "Es un actions para hacer un checkout de cualquier repo git solo se requiere usuario y contraseña."
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
    repository:
      description: 'URL del repositorio'
      required: true
      default: 'https://'
    password:
      description: 'Contraseña del repositorio'
      required: true

runs:
  using: 'composite'
  steps:
    - run: git clone https://${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@gitlab.com/${{ github.event.inputs.repository }}/${{ github.event.inputs.password }}.git
      shell: bash
