name: "CheckoutRepoGit"
description: | 
  "Es un actions para hacer un checkout de cualquier repo git solo se requiere usuario y contraseña."
branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - run: |
        git clone https://${{ inputs.INPUT_USER_REPO }}:${{ inputs.INPUT_PASS_REPO }}@${{ inputs.INPUT_URL_REPO }}
      shell: bash