name: "CheckoutRepoGit"
description: | 
  "Es un actions para hacer un checkout de cualquier repo git solo se requiere usuario y contraseña."
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  num-octocats:
    description: 'Number of Octocats'
    required: false
    default: 'hola'
  octocat-eye-color:
    description: 'Eye color of the Octocats'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        echo $num-octocats
        git clone https://${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}:${{ secrets.PASSREPO_API_SAMPLE_ANTHONY }}@Labs-DevOps@gitlab.com/${{ vars.USER_REPO_API_SAMPLE_ANTHONY }}/${{ vars.REPO_API_SAMPLE_ANTHONY }}.git
      shell: bash