name: "CheckoutRepoGit"
description: | 
  "Es un actions para hacer un checkout de cualquier repo git solo se requiere usuario y contraseña."
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  var1:
    description: 'Number of Octocats'
    required: true
    default: 'variable01'
  var2:
    description: 'Eye color of the Octocats'
    default: 'variable02'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        export $INPUT_VAR = "Valor 1"
        env
        echo $INPUT_VAR
      shell: bash