name: "CheckoutRepoGit"
description: | 
  "Es un actions para hacer un checkout de cualquier repo git solo se requiere usuario y contraseña."
branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - run: |
        git clone https://$INPUT_USER_REPO:$INPUT_PASS_REPO@$INPUT_URL_REPO
      shell: bash