name: "CheckoutRepoGit"
description: | 
  "Es un actions para hacer un checkout de cualquier repo git solo se requiere usuario, contraseña y la url."
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  user_repo:
    description: 'Usuario del repositorio'
    required: true
  pass_repo:
    description: 'contraseña del repositorio'
    required: true
  url_repo:
    description: 'URL del repositorio'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        env
        echo "${{ inputs.user_repo }}"
        echo "${{ inputs.INPUT_USER_REPO }}"
      shell: bash